### PR TITLE
Add short section on METS

### PR DESCRIPTION
**Pull request by stuartyeates**
Still summer holidays here, so I've not been able to validate this TEI/ XML, but it looks OK. Feel free to copy edit as necessary.

### CODE REVIEW

**Review by lb42 — COMMENTED** [review]
I dont think this adds anything and is very vague. What does "direct support" mean? Where is the word "TEIHDR" specified in METS? Does the cookbook specify how this MIGHT be done, or how it CAN be done: presumably only the former if there is no "significant support for TEI Headers". So what are we saying? That if you want to include a TEI Header in your METS package you can if you call it a "TEIHDR"?

**Comment by stuartyeates** [comment]
TEIHDR is specified in the METS documentation and schema,see http://www.loc.gov/standards/mets/docs/mets.v1-9.html#mdWrap . The same document talks about TEI documents in a number of use cases,as does the official overview and tutorial at http://www.loc.gov/standards/mets/METSOverview.v2.html

**Comment by lb42** [comment]
Thanks for the quick clarification Stuart, but I'm still a bit unsure what it is meant by "support" in your comment.

**Comment by stuartyeates** [comment]
None of the implementations that I'm aware of actually do anything useful with the TEIHDR in the METS. They pass it through and preserve it (possibly moving it from dmdSec to sourceMD (indicating that this block of metadata is not current but corresponds to the object at some 'source' point in time)) but they don't use it for search, display, access, control, etc. They typically use DC (most implementations) or EAC/EAD (those in the archival world) for these fucntions

**Comment by emylonas** [comment]
@sydb  and I looked it over. It's fine to merge. However, post merge, would make following tweak: 
change `that is complete  <gi>teiHeader</gi> tags can be included in METS metadata alongside MARC, MODS and DC. METS specifies 'TEIHDR' to indicate a TEI Header. `
to
` that is a complete <gi>teiHeader</gi> element can be included in METS metadata alongside MARC, MODS and DC. METS specifies 'TEIHDR' to indicate a TEI Header. `

**Pull request merged**
