### PR TITLE
merge bibliographic changes

### PR DESCRIPTION
**Pull request by emylonas**

### CODE REVIEW

**Review by sydb — APPROVED** [review]
I don’t like the phrasing “XInclude or URI references”, but that's wordsmithing we can address later.
(Oh dear — this comment was intended for b4bb36a only.)

**Review by sydb — APPROVED** [review]

**Review by sydb — APPROVED** [review]
d51b461769671784e5d2e98dcf6b8dc3faddc2a0 seems fine

**Review by sydb — APPROVED** [review]
Change in 72250385dafc8a57c178c15dc6e7277204572c26 does not seem to matter (at least, not using Firefox on Ubuntu GNU/Linux)

**Review by sydb — APPROVED** [review]
Approving 8755b076e9cc7ab7a1427ba2a237faa7427f8988, but we should add phrase-level encoding for the value.

**Review by sydb — APPROVED** [review]
OK. (59845f7e077f3613b159962ca5beaaabb7975057)

**Review by sydb — APPROVED** [review]
OK. (3892ababdd394efa5bcb1454c60cf96563990fdb)

**Review by sydb — COMMENTED** [review]
This (e160760) seems like an error — like new content was added w/o deleting the old.

**Comment by kshawkin** [comment]
Comments on Syd's comments ...

a) Regarding https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/b4bb36a9ff6b0b1260b68351f461d68a282a3068 , let's improve “XInclude or URI references”.

b) Regarding https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/72250385dafc8a57c178c15dc6e7277204572c26 , you're right that both render the same, but we had a brief discussion about which is canonical and decided to change.

c) Regarding https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/8755b076e9cc7ab7a1427ba2a237faa7427f8988 , which value are you talking about?

d) Regarding https://github.com/kshawkin/Best-Practices-for-TEI-in-Libraries/commit/e1607603903cff7091baae79bc0edf480153b7ee , I see a lot of unrelated changes, but I can't imagine that they're all in error ...

**Comment by emylonas** [comment]
a) b4bb36a belongs to #16. had made some improvements, could use more.
 
b) agree with @kshawkin - the second is more canonical

c)  this is likely in progress

d) I think this may come from a merge - most of the changes aren't mine.

**Comment by emylonas** [comment]
all fixed but don't understand this comment `Approving 8755b07, but we should add phrase-level encoding for the value.` @sydb it's from above.

**Comment by kshawkin** [comment]
For the record, Elli said on 2018-02-13 that she and Syd sorted out the thing that confused them while solving another problem.

**Pull request merged**
